### ISSUE TITLE
Error using Swap Voice and Clone Voice on Apple Silicon M2

### ISSUE THREAD

**Issue by winterhuette** [C0untFloyd/bark-gui#77]
I receive the following error when starting webui.py -enablemps on my Mac mini with M2 CPU. This only happens with Swap or Clone Voice. TTS works fine.

File "/Users/jan/anaconda3/lib/python3.11/site-packages/torch/serialization.py", line 165, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

I does not seem to load the Hubert_model into MPS but tries to use CUDA (that I do not have).
Do I need to adjust the code somewhere? I thought it would be enough to set the -enablemps switch.

Thank you very much for your support.

**Comment by winterhuette** [comment]
I solved this by replacing  the line "model.load_state_dict(torch.load(path))" with "model.load_state_dict(torch.load(path, map_location='mps'))" in file "customtokenizer.py" in folder "/bark-gui/bark/hubert/". Hope this helps others.

**Comment by denisroldan** [comment]
This worked for me on a M1 Pro 😉

**Comment by AIhasArrived** [comment]
Hello @winterhuette  and @denisroldan  , were you able to finish the installation? If yes, can you tell me what models were downloaded? I can't get them. Furthermore, would you upload them to some provider and send me link to download them please? My installation is stuck at this:
![image](https://github.com/C0untFloyd/bark-gui/assets/148225825/c5419467-5ce6-4851-863d-ad7b777cc558)
And it does not advance afterwards, nothing happens, I have been waiting for a hour or so..
